name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        default: ""

env:
  NODE_VERSION: '20.12'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ env.cache-version }}-${{ runner.os }}-build-
            ${{ env.cache-version }}-${{ runner.os }}-
      - name: Install Dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          npm install
      - name: Build
        run: npm run build
      - name: Create zip
        run: |
          npm run deploy
          ren vrchat-join-notifier.zip vrchat-join-notifier-v${{ github.event.inputs.version }}-win10-x64.zip
      - name: Create a GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          body: vrchat-join-notifier@${{ github.event.inputs.version }} is Released. Download **vrchat-join-notifier-v${{ github.event.inputs.version }}-win10-x64.zip**
      - name: Upload Release Asset - windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vrchat-join-notifier-v${{ github.event.inputs.version }}-win10-x64.zip
          asset_name: vrchat-join-notifier-v${{ github.event.inputs.version }}-win10-x64.zip
          asset_content_type: application/zip
