name: publish
env:
  CI: true

on:
  push:
    branches:
      - master
    paths:
      - package.json

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ env.cache-version }}-${{ runner.os }}-build-
            ${{ env.cache-version }}-${{ runner.os }}-
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Get version of package.json
        id: version
        run: |
          LATEST_VERSION=`cat package.json | jq -r '.version'`
          echo "::set-output name=LATEST_VERSION::$LATEST_VERSION"
      - name: Create zip
        run: |
          ./node_modules/.bin/nexe lib/winExe.js --target 12.18.2 -o dist/vrchat-join-notifier-v${{ steps.tag.outputs.version }}-win10-x64.zip
          zip -r vrchat-join-notifier-v${{ steps.tag.outputs.version }}-win10-x64.zip dist/
      - name: Create a GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.LATEST_VERSION }}
          release_name: Release ${{ steps.version.outputs.LATEST_VERSION }}
          body: ${{ steps.version.outputs.LATEST_VERSION }}
      - name: Upload Release Asset - windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vrchat-join-notifier-v${{ steps.tag.outputs.version }}-win10-x64.zip
          asset_name: vrchat-join-notifier-v${{ steps.tag.outputs.version }}-win10-x64.zip
          asset_content_type: application/zip
